name: Elixir CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    container:
      image: elixir:1.9.4-alpine
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix do deps.get, deps.compile
        apk add --no-cache make
    - name: Unit Tests
      run: make unit-test
